### ISSUE TITLE
Build with C++11 support?

### ISSUE THREAD

**Issue by jdemeyer** [conda-forge/fplll-feedstock#5]
I am having trouble running `fpylll` with this `fplll` for ReadTheDocs. The error I get is
```
ImportError: /home/docs/checkouts/readthedocs.org/user_builds/fpylll/conda/latest/lib/python2.7/site-packages/fpylll/fplll/bkz_param.so: undefined symbol: _ZN5fplll18strategy_full_pathERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE
```
See https://readthedocs.org/projects/fpylll/builds/5290061/ (note that you need to open the second last box about `sphinx-build` to see the problem)

I *guess* that this is because `fplll` is not compiled with `-std=c++11` while `fpylll` is compiled with `-std=c++11` and this leads to incompatibilities.

Obvious question: are you sure that https://github.com/conda-forge/fpylll-feedstock actually works (in particular, did you run the testsuite for `fpylll`)?

CC @malb

**Comment by malb** [comment]
FWIW fplll won't compile without C++11

**Comment by jdemeyer** [comment]
Well, to be honest, I have no idea what the problem is...

*Something* is different between the conda-forge build environment and the readthedocs build environment.

**Comment by isuruf** [comment]
Is this using gcc 5.x?

**Comment by jdemeyer** [comment]
readthedocs uses Ubuntu 16.04 which ships with g++ 5.4.0

**Comment by isuruf** [comment]
Right. Then this is a problem with gcc ABI which changed from 4.x to 5.x. conda-forge packages are all compiled with gcc 4.8.*

You have 2 options,
1. Install gcc 4.x
2. Since gcc 5.x has dual ABI, you can ask it to use the 4.x ABI.
 `export CPPFLAGS="-D_GLIBCXX_USE_CXX11_ABI=0"` should change it to the old ABI.

**Comment by jdemeyer** [comment]
Wonderful! Why is C++ so hard :-)
