### ISSUE TITLE
Upgrade to 5.2.0

### ISSUE THREAD

**Issue by jdemeyer** [conda-forge/fplll-feedstock#7]
See https://github.com/fplll/fplll/releases

**Comment by isuruf** [comment]
PRs welcome! Just need to change the version and sha256 checksum here, https://github.com/conda-forge/fplll-feedstock/blob/master/recipe/meta.yaml

**Comment by isuruf** [comment]
Done in https://github.com/conda-forge/fplll-feedstock/pull/8
